### ISSUE TITLE
cancelPendingPaymentOrders does not exist

### ISSUE THREAD

**Issue by durzel** [ebizmarts/sage-pay-suite-ce#19]
The function "cancelPendingPaymentOrders", needed by the new functionality provided by "Cancel Pending Payment Orders Cron" does not exist anywhere.  As a result - enabling this option results in a cron error:

> Cron error while executing sagepaysuite_cancel_pending_payment_orders:
>
> exception 'Mage_Core_Exception' with message 'Invalid callback: Method for sagepaysuite/cron::cancelPendingPaymentOrders does not exist' in /home/magento/public_html/app/Mage.php:595</addr>

I would presume it is supposed to be in  [sage-pay-suite-ce/app/code/local/Ebizmarts/SagePaySuite/Model/Cron.php](https://github.com/ebizmarts/sage-pay-suite-ce/blob/master/app/code/local/Ebizmarts/SagePaySuite/Model/Cron.php) - since that's where the syncApi function resides?

**Comment by martinebiz** [comment]
it seems the file was not correctly merged, we'll be releasing a new fixed version today.

**Comment by durzel** [comment]
Thanks - can confirm 3.6.2 resolves this issue.
