### ISSUE TITLE
Issue after magento update

### ISSUE THREAD

**Issue by scottblackburn** [ebizmarts/sage-pay-suite-ce#25]
Hi,

Since upgrading magento to 1.9.3.1 i'm getting an exception from the sage pay suite extension, i've upgraded the sage pay extension at the same time. 

`exception 'Exception' with message 'String could not be parsed as XML' in /Users/sblackburn/projects/handset-solutions/public/app/code/local/Ebizmarts/SagePaySuite/Model/Feed/Updates.php:35`

Is the plugin compatible with this version of magento?

Any help is appreciated.

**Comment by ebizmarts-keller** [comment]
We are going to look into this. But please open a thread on the forums, we'll continue this there.

https://ebizmarts.com/forums/view/2
