### ISSUE TITLE
Issue with send email config

### ISSUE THREAD

**Issue by udovicic** [ebizmarts/sage-pay-suite-ce#4]
Ebizmarts_SagePaySuite_Model_SagePayForm on line [172](https://github.com/ebizmarts/sage-pay-suite-ce/blob/master/app/code/local/Ebizmarts/SagePaySuite/Model/SagePayForm.php#L172) has typo in word _'SendEmail'_ (capital __M__) and wrong type casting(should be __string__ instead of __int__):

```php
$data['SendEMail']    = (int)$this->getConfigData('send_email');
```

should be:

```php
$data['SendEmail']    = (string)$this->getConfigData('send_email');
```

As a result, email is being sent to customer, regardless configuration in admin.

**Comment by martinebiz** [comment]
Thanks for your input udovicic, this has already been fixed for our next release.

**Comment by udovicic** [comment]
No problem. I was just installing 3.0.24.3 and noticed it is still there.

**Comment by martinebiz** [comment]
Thanks for the heads up. Cheers
