### ISSUE TITLE
Load quote from qid

### ISSUE THREAD

**Issue by udovicic** [ebizmarts/sage-pay-suite-ce#5]
Ebizmarts_SagePaySuite_Model_Api_Payment on line [357](https://github.com/ebizmarts/sage-pay-suite-ce/blob/master/app/code/local/Ebizmarts/SagePaySuite/Model/Api/Payment.php#L357) appends new quote to existing quote object, instead of replacing one inside session:

```php
$opQuote->setQuote(Mage::getModel('sales/quote')->loadActive($rqQuoteId));
```

Since _$opQuote_ is quote object, _setQuote()_ appends new one to its _data protected array (magic function inside Varien_Object). Instead of that, _setQuote()_ should have been called on checkout session:

```php
Mage::getSingleton('checkout/type_onepage')->setQuote(
    Mage::getModel('sales/quote')->loadActive($rqQuoteId)
);
```

**Comment by martinebiz** [comment]
Thanks for your input udovicic, we'll take this into account for next release.

**Comment by udovicic** [comment]
Actually, there is one more critical issue here:
_ _getQuote()_ function of _Ebizmarts_SagePaySuite_Model_Api_Payment_ is being called several times during _notifyAction()_ of SERVER integration.

Since [conditions](https://github.com/ebizmarts/sage-pay-suite-ce/blob/master/app/code/local/Ebizmarts/SagePaySuite/Model/Api/Payment.php#L356) for loading quote do not check if quote has been previously loaded, this always results in reloading the quote. Since this new quote is treated as different object on PHP level, all flags that have been previously set are being discarded(or more precisely, this is  new object now, they have never been set on it).

On of the results of this is that inventory is being deducted twice, as it depends on _InventoryProcessed_ flag.

**Comment by martinebiz** [comment]
we are not getting inventory issues when using SERVER, nonetheless we'll check if this can be causing any issues.
