### ISSUE TITLE
Session unavailable causing server integration to always fail

### ISSUE THREAD

**Issue by udovicic** [ebizmarts/sage-pay-suite-ce#6]
_ServerPaymentController_ inside _notifyAction()_ function on line [322](https://github.com/ebizmarts/sage-pay-suite-ce/blob/master/app/code/local/Ebizmarts/SagePaySuite/controllers/ServerPaymentController.php#L322) verifies cart consistency. This is done by helper, which depends on session due to _last_vendor_tx_code_ value which is being stored there, as seen [here](https://github.com/ebizmarts/sage-pay-suite-ce/blob/master/app/code/local/Ebizmarts/SagePaySuite/Helper/Checkout.php#L43).

Since _notifyAction()_ is being called by SagePay server, session is no longer available due to new security measures introduced by latest Magento, which prevents resuming of session by SID get parameter on secure links.

As a result, _SERVER_ integration is render unusable because _cartExpire()_ will always return true, due to unavailability of data from session.

**Comment by centerax** [comment]
Thanks Stjepan for reporting this issue, we will let you know when we have news.
