### ISSUE TITLE
Some invoices don't get generated.

### ISSUE THREAD

**Issue by kevdotbadger** [ebizmarts/sage-pay-suite-ce#7]
seems that a few people are having issues with Magento calling ebizmarts_SagePaySuite_Model_SagePayForm::captureInvoice() despite it not existing (although I think it might have been renamed to capture()).

It seems to be called on /var/www/vhosts/domain.com/public_html/app/code/local/Ebizmarts/SagePaySuite/Model/SagePayForm.php(259): Varien_Object->__call('captureInvoice', Array)

duping the ::capture() and renaming it to ::captureInvoice() seems to fix the issue.

**Comment by martinebiz** [comment]
we have corrected this for next release.
